[package]
name = "luxo-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
tracing = "0.1"
tracing-subscriber = "0.3"
thiserror = "1.0"
nix = { version = "0.29", features = ["fs"] }

[dev-dependencies]
tempfile = "3"