[package]
name = "luxo-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
cfg-if = "1.0"
memmap2 = "0.9"
num = "0.4"
nix = { version = "0.29", features = ["feature", "fs"] }
thiserror = "1.0"
tracing = "0.1"
tracing-subscriber = "0.3"

[dev-dependencies]
tempfile = "3"